---
blank_issues_enabled: false
contact_links:
  - about: 'Use the Loonflow Community Discord for questions & discussions'
    name: Questions
    url: 'https://discord.gg/dh8vBG6J'
  - about: 'Please check the FAQ before filing new issues'
    name: 'Loonflow FAQ'
    url: '#'
